all : config2cy.tab.c config2cl.lex.c config2cy.tab.h

config2cy.tab.c config2cy.tab.h : config2cy.y
	yacc -d -b config2cy config2cy.y

config2cl.lex.c : config2cl.l
	lex -t config2cl.l > config2cl.lex.c

clean :
	rm config2cy.tab.c config2cy.tab.h config2cl.lex.c
